Talk(0, "이 조각상의 여인은 너무나도 아름답군…！ 아！ 밑에 글귀가 있구나。 \"천 번 절하고 내 명에 따르면 후회하지 않는다。\" 미쳤군！ 누가 조각상에다 천 번이나 절을 한다고！'", "talkname0", 1);
if InTeam(53) == true then goto label0 end;
    do return end;
::label0::
    jyx2_ReplaceSceneObject("", "NPC/段誉11", "1");--段誉出现
    Talk(53, "신선 누님！ 소생 단예가 오늘 당신의 아름다운 얼굴을 봤니 죽어도 여한이 없습니다。 누님， 혼자 이곳에서 살면 쓸쓸하지 않나요？", "talkname53", 1);
    Talk(0, "단 형， 옥상과 얘기하고 있는 거요？ '드디어 이 바보가！'", "talkname0", 1);
    Talk(53, "뇌고산에 신선이 사니 옥과 같은 피부에 이슬과 바람만 먹고살았노라。 신선 누님， 당신이 살아서 저에게 한마디 말이라도 걸어주신다면 마치 극락에 온 것만 같은 기분일 겁니다。 저는 당신을 위해 천 번， 만 번도 죽을 수 있습니다… 천 번의 절 즘이야 당연히 올려야죠…", "talkname53", 1);
    DarkScence();
    ModifyEvent(-2, 0, -2, -2, -2, -2, -2, 6316, 6316, 6316, -2, -2, -2);
    jyx2_SwitchRoleAnimation("NPC/段誉11", "Assets/BuildSource/AnimationControllers/KneelController.controller");
	jyx2_MovePlayer("观看段誉磕头","Level/Dynamic");
    LightScence();
    PlayAnimation(0, 6316, 6334);
    PlayAnimation(0, 6316, 6334);
    jyx2_SwitchRoleAnimation("NPC/段誉11", "Assets/BuildSource/AnimationControllers/备份/DuanyuKneelController.controller");
    Talk(0, "단 형！ 지금 뭐 해？ 정말 천 번 절을 올리려고 하는구나！", "talkname0", 1);
    Talk(53, "십， 십일， 십이……", "talkname53", 1);
    PlayAnimation(0, 6316, 6334);
    PlayAnimation(0, 6316, 6334);
    PlayAnimation(0, 6316, 6334);
    Talk(0, "미친다 미치어！", "talkname0", 1);
    DarkScence();
    ModifyEvent(-2, 0, -2, -2, -2, -2, -2, 6338, 6338, 6338, -2, -2, -2);
	jyx2_ReplaceSceneObject("", "Dynamic/Chair_11", "");--需要替换破烂的蒲团
    ModifyEvent(-2, 11, -2, -2, -2, -2, -2, 6312, 6312, 6312, -2, -2, -2);
    jyx2_SwitchRoleAnimation("NPC/段誉11", "Assets/BuildSource/AnimationControllers/备份/DuanyuController.controller");
    LightScence();
    Talk(0, "미친다 미치어！ 형제， 정말 천 번이나 절을 했구나！ 머리는 괜찮아？ 방석이 다 찢어졌네！", "talkname0", 1);
    Talk(53, "아니？！ 방석 속에 뭔가 들어 있는데？！ 뭔가 적혀있어…… \"절을 천 번 한 자에게는 상을 내리노라。 이것은 소요파의 무공이니 매일 아침， 점심， 저녁에 연마하거라……", "talkname53", 1);
    Talk(0, "책이 두 권 들어있군。 한 권은 \"북명신공\"이고， 다른 건 \"능파미보\"？", "talkname0", 1);
    Talk(53, "무공을 배우기는 싫지만 신선 누나의 명을 거역할 순 없지！。 절을 올렸으니 이젠 명령에 따를 수밖에。 책에 뭐라고 쓰여있나 봐야지。' \"태고에 북쪽에 명해가 있었다… 북명신공은 세인의 힘을 내 것으로 만드는 위대한 힘이다。 천 개의 강이 모여 바다가 되고 바다는 한없이 물을 받아들인다。 먼저 정신집중하여 손을 태음폐경에 놓아라。 …………혈도 그림이 있고 경맥선까지 그려져 있구나…… 아！ 몸이 갑자기 뜨거워져！…… \"능파미보\"에는 발자국 모양을 많이 그려 놓았군。 역경 중의 방위까지 해석 해놓았구나。 마침 며칠 전 역경을 공부했더니 쉽게 익힐 수 있겠는데……？", "talkname53", 1);
    DarkScence();
    LightScence();
    Talk(53, "신선 누님， 당신께서 저에게 무공을 연마하라 하셨으니 분부대로 아침， 점심， 저녁마다 열심히 수련하겠습니다。", "talkname53", 1);
    Talk(0, "단형， 생각을 바꿔 무공을 익히려고 하는군。", "talkname0", 1);
    Talk(53, "모두에게 친절을 베풀면 날 때리지 않을 테니 내력을 뺏을 필요가 없지。 상황이 급해 수 틀리면 도망가야 하니 능파미보를 열심히 수련해야겠어。", "talkname53", 1);
    Talk(0, "마음대로！ 얼른 떠납시다。", "talkname0", 1);
    DarkScence();
    ModifyEvent(-2, 11, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    jyx2_ReplaceSceneObject("", "NPC/段誉11", "");--段誉归队
    LightScence();
    AddItem(63, 1);
    AddItem(47, 1);
    LearnMagic2(53, 29, 0);
    AddSpeed(53, 30);
    AddAttack(53, 10);
    AddAptitude(53, 20);
    SetPersonMPPro(53,2);
    ModifyEvent(-2, 1, -2, -2, 485, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 2, 1, 1, -1, -1, -1, 6752, 6752, 6752, -2, -2, -2);
    jyx2_ReplaceSceneObject("", "NPC/蟒牯朱蛤", "1");
    ModifyEvent(-2, 3, -2, -2, -1, -1, 486, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 4, -2, -2, -1, -1, 486, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 5, -2, -2, -1, -1, 486, -2, -2, -2, -2, -2, -2);
    SetScenceMap(52, 1, 27, 28, 1842);
    SetScenceMap(52, 1, 27, 20, 1838);
    SetScenceMap(52, 1, 27, 29, 0);
	jyx2_FixMapObject("燕子坞开门",1);
    PlayWave(21);
do return end;
