PlayAnimation(3, 6342, 6348);
jyx2_SwitchRoleAnimation("NPC/suxinghe", "Assets/BuildSource/AnimationControllers/KneelController.controller");
Talk(52, "소요파 불초한 제자 소성하가 본파의 신임 장문을 뵙습니다。", "talkname52", 0);
Talk(49, "대선배께서 소승에게 절을 하시다니 가당치 않습니다。", "talkname49", 0);
Talk(52, "사제는 사부님의 제자요， 본파 장문이니， 사형인 나도 절을 해야 한다。", "talkname52", 0);
Talk(49, "이거… 이거…", "talkname49", 0);
Talk(52, "사부님을 모시게 되어 아홉 번 절하라 하셨는데 절을 올렸나？", "talkname52", 0);
Talk(49, "그 게， 절은 올렸지만 입문 절차란 것을 몰랐어요。 난 소림사 제자라 개파할 수 없습니다。", "talkname49", 0);
Talk(52, "사부님도 알고 계시다。 그래서 소림사 무공을 지우고 필생의 공력과 무공을 물려주신 게야。 안 그런가？", "talkname52", 0);
Talk(49, "마… 맞습니다。", "talkname49", 0);
Talk(52, "또한 본파 장문인의 신분을 증명하는 칠보지환을 자네 손에 끼워 주셨다。 안 그런가？", "talkname52", 0);
Talk(49, "맞아요！ 하지만 난 그런 사실을 하나도 몰랐어요！", "talkname49", 0);
Talk(52, "사제는 복도 많구먼。 나와 정춘추는 몇 십 년 동안 반지를 탐냈거늘 사제는 하루 만에 사부님한테서 받았으니 말이야！", "talkname52", 0);
Talk(49, "그럼 가져가세요。 소승에겐 반지가 조금도 쓸모 없습니다。", "talkname49", 0);
Talk(52, "사제여， 기어코 사부님의 임종을 헛되이 만들건가？ 사부님의 유지를 어길텐가！ 반지를 주면서 정춘추를 제거하라 하지 않았나？", "talkname52", 0);
Talk(49, "네。 그러나 소승은 무공이 얕은 데다 자신도 없는데 어떻게 중임을 맡을 수 있겠습니까？", "talkname49", 0);
Talk(0, "아니？ 동생이 한 문파의 장문이 되었다고？！ 잘 됐군！", "talkname0", 1);
Talk(49, "형님， 전…", "talkname49", 0);
ModifyEvent(-2, -2, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
do return end;
