ScenceFromTo(44, 24, 36, 24);
jyx2_CameraFollow("Level/NPC/azi");
Talk(92, "사매， 널 데려오라는 사부님의 명령이다！ 거역하지 마라！", "talkname92", 0);
Talk(47, "둘째 사형， 사부님이 역정 내실 텐데 돌아가라니！ 내가 혼나길 바라요？", "talkname47", 0);
Talk(92, "가기 싫다면 물건을 내놔라！ 그래야 사부님이 벌을 안 내릴 거야。", "talkname92", 0);
Talk(47, "무슨 물건？ 맞아！ 사형 뒤에 있는 자가 훔쳐 갔어요！", "talkname47", 0);
Talk(92, "이놈아！ 어서 신목왕정을 내놔라！", "talkname92", 0);
ScenceFromTo(36, 24, 44, 24);
jyx2_CameraFollowPlayer();
Talk(0, "………………이것들이 뭐라는 거냐！", "talkname0", 1);
Talk(47, "사형， 훔쳐 간 물건을 쉽게 내놓겠어요？", "talkname47", 0);
Talk(92, "날 원망하지 마라！", "talkname92", 0);
Talk(0, "난 왜 가는 곳마다 이런 놈들만 꼬이는 거야？", "talkname0", 1);
if TryBattle(87) == true then goto label0 end;
    Dead();
    do return end;
::label0::
    ModifyEvent(-2, 5, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 6, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 7, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 8, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 9, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    jyx2_ReplaceSceneObject("", "NPC/星宿弟子5", "");
    jyx2_ReplaceSceneObject("", "NPC/星宿弟子6", "");
    jyx2_ReplaceSceneObject("", "NPC/星宿弟子7", "");
    jyx2_ReplaceSceneObject("", "NPC/星宿弟子8", "");
    jyx2_ReplaceSceneObject("", "NPC/星宿弟子9", "");
    ModifyEvent(-2, 4, -2, -2, -2, -1, -1, 6378, 6378, 6378, -2, 35, 24);
    jyx2_SwitchRoleAnimation("NPC/youtanzhi", "Assets/BuildSource/AnimationControllers/StandController.controller");
    jyx2_FixMapObject("移到阿紫身边", 1);
    SetScencePosition2(37, 25);
	jyx2_MovePlayer("战斗后","Level/Dynamic");
    LightScence();
    Talk(0, "낭자， 이 게 무슨 일이오？", "talkname0", 1);
    Talk(47, "사형이 절 죽이려 했는데 당신이 구해주신 거죠。", "talkname47", 0);
    Talk(0, "난 신목왕정을 훔친 적이 없소。", "talkname0", 1);
    Talk(47, "내가 그들을 속인 덕분이죠。 안 그랬다면 당신이 어떻게 날 구했겠어요？", "talkname47", 0);
    Talk(0, "아니… 거짓말이 너무 심하군… 내가 무공을 못했으면 맞아 죽었을 게 아니오？", "talkname0", 1);
    Talk(47, "그들도 못 이긴다면 차라리 죽는 게 낫죠。", "talkname47", 0);
    Talk(0, "아니… 뭐라고？", "talkname0", 1);
    Talk(47, "됐어요！ 철추！ 저기서 빙잠을 잡았다고 했지？ 나도 하나 잡아서 수련해야겠다。", "talkname47", 0);
    Talk(48, "빙잠을 잡았던 뚱보 화상이 곤륜에서 잡은 거라고 했어요。", "talkname48", 0);
    Talk(47, "네가 빙잠의 정기를 모두 흡수하는 바람에 내가 수련을 못 하잖아！", "talkname47", 0);
    Talk(48, "소인의 죄입니다。", "talkname48", 0);
    Talk(0, "이 계집은 십중팔구 어떤 음독한 무공을 연마하는 모양이군'", "talkname0", 1);
    Talk(47, "이봐요， 볼 일 다 봤으면 어서 꺼질 것이지 왜 계속 거기 있어요？", "talkname47", 0);
    Talk(48, "아가씨 말씀을 들어라！", "talkname48", 0);
    Talk(0, "생명의 은인을 내쫓다니 별 흉악한 사람도 다 있군。", "talkname0", 1);
    Talk(47, "제법 남자다운 면이 있었네？ 철추！ 저놈을 잡아 가면을 씌워 노예로 만들어라！", "talkname47", 0);
    Talk(48, "아가씨， 저 혼자 모실 테니 다른 노예는 구하지 마세요。", "talkname48", 0);
    Talk(47, "시키는 대로 할 것이지 감히 말대답을 해？", "talkname47", 0);
    Talk(48, "바로 하는 중입니다。", "talkname48", 0);
    Talk(0, "참을 수가 없네。 날 노예로 삼겠다고？ 건방진 계집！ 늬넨 안되겠다…", "talkname0", 1);
    if TryBattle(88) == true then goto label1 end;
        Dead();
        do return end;
::label1::
        LightScence();
        Talk(48, "아가씨， 죄송한데 전 상대가 안 되네요。", "talkname48", 0);
        Talk(47, "이런 바보！ 도대체 할 줄 아는 게 뭐야？", "talkname47", 0);
        Talk(0, "재수 없는 날이야。 여기 계속 있다간 미쳐버릴 것 같아' 난 가겠다！", "talkname0", 1);
        ModifyEvent(-2, 3, -2, -2, 558, 560, -1, -2, -2, -2, -2, -2, -2);
        ModifyEvent(-2, 4, -2, -2, 559, -1, -1, -2, -2, -2, -2, -2, -2);
        ModifyEvent(-2, 0, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
        ModifyEvent(-2, 1, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
        ModifyEvent(-2, 2, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
        AddEthics(2);
        AddRepute(2);
do return end;
