if UseItem(131) == true then goto label0 end;
    do return end;
::label0::
    AddEthics(2);
    AddItemWithoutHint(131, -1);
    Talk(51, "하하하！ 대연황제도표와 옥새만 있으면 나라를 수복할 수가 있다！", "talkname51", 0);
    Talk(0, "모용 공자， 이 번엔 한 말을 어기지 않겠지？", "talkname0", 1);
    Talk(51, "나 모용복은 신의가 있는 사람이다。", "talkname51", 0);
    Talk(0, "누가 믿겠니？'", "talkname0", 1);
    Talk(51, "\"천룡팔부\" 가 있는 곳은……", "talkname51", 0);
    Talk(0, "어디 있소？", "talkname0", 1);
    Talk(51, "교봉의 손에 있다。", "talkname51", 0);
    Talk(0, "개방 방주 교봉？", "talkname0", 1);
    Talk(51, "맞아。", "talkname51", 0);
    Talk(0, "강호에 도는 \"남모용， 북교봉\" 이란 말 때문에 거짓말하는 게 아니냐？", "talkname0", 1);
    Talk(109, "오라버니는 거짓말 안 해요。 정말 교봉이 갖고 있어요。", "talkname109", 0);
    Talk(0, "왕 낭자의 하는 말이니 믿을 수 있겠어。 당장 개방으로 가야지！", "talkname0", 1);
    Talk(51, "틀렸다。 소림사로 가는 게 급선무야。", "talkname51", 0);
    Talk(0, "어째서지？", "talkname0", 1);
    Talk(51, "묻겠다。 너 따위가 교봉을 이길 자신이 있나？", "talkname51", 0);
    Talk(0, "그래도 싸우는 수밖에 없어。", "talkname0", 1);
    Talk(51, "교봉이 순순히 책을 내놓게 하는 방법이 있다。", "talkname51", 0);
    Talk(0, "그 게 어떤 방법이지？", "talkname0", 1);
    Talk(51, "그의 비밀을 알고 있다。 지금까지의 명성을 잃게 될 치명적인 비밀이지！", "talkname51", 0);
    Talk(0, "그럼 왜 소림사로 가야 하는 거지？", "talkname0", 1);
    Talk(51, "소림사에서 먼저 가져올 물건이 있다。", "talkname51", 0);
    Talk(0, "무슨 물건？", "talkname0", 1);
    Talk(51, "무림이 발칵 뒤집어질 만한 물건이지。 나와 같이 가자。 그럼 책을 빨리 찾을 수 있다。 너 혼자 교봉을 이길 자신이 있냐？", "talkname51", 0);
    Talk(0, "그런데 왜 날 돕는 거지？", "talkname0", 1);
    Talk(51, "나 혼자 힘으론 잃은 나라를 수복하는 큰 꿈을 이루기 힘들다。 무림이 혼란한 틈을 노린다면 일말의 기회가 있지。 너도 그 속에서 원하는 걸 얻을 수 있을거다。", "talkname51", 0);
    Talk(109, "오빠！ 단녕하세요。 세상을 어지럽히게 될 뿐이에요。", "talkname109", 0);
    Talk(51, "닥쳐！ 나 모용복의 복자가 무슨 뜻인 줄 아느냐？ 모용 가문이 대대로 무엇을 위해 여태 살아왔느냐？ 어때， 나와 손을 잡겠나？", "talkname51", 0);
    ModifyEvent(-2, 5, -2, -2, 497, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, -2, -2, -2, 494, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 2, -2, -2, 495, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(51, 14, -2, -2, 527, 531, -1, -2, -2, -2, -2, -2, -2);
    if AskJoin () == true then goto label1 end;
        Talk(0, "공자의 뜻은 고맙소만 난 내 힘으로 정정당당하게 교봉과 무공을 겨루겠소。 비겁한 수단으로 \"천룡팔부\"를 얻고 싶은 마음은 없다。", "talkname0", 1);
        Talk(51, "잘 생각해 봐라。", "talkname51", 0);
        do return end;
::label1::
        Talk(0, "좋다。 함께 소림사로 가서 교봉의 비밀을 벗기자。", "talkname0", 1);
        if TeamIsFull() == false then goto label2 end;
            Talk(51, "일행이 많으니 다음에 합류하겠다。", "talkname51", 0);
            do return end;
::label2::
            DarkScence();
            jyx2_ReplaceSceneObject("", "NPC/慕容复", "");--慕容复
            ModifyEvent(-2, -2, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
            ModifyEvent(-2, 2, -2, -2, 495, -1, -1, -2, -2, -2, -2, -2, -2);
            LightScence();
            Join(51);
do return end;
