Talk(97, "감히 신룡도를 침입한 자가 누구냐！", "talkname97", 0);
Talk(0, "신룡도？ 왠지 무섭게 들리는군。 얼른 튀자。", "talkname0", 1);
Talk(97, "서라！ 여기 신룡도는 네가 오면 오고， 가면 갈 수 있는 그런 곳이 아니야。", "talkname97", 0);
Talk(0, "사납게 구는군。 배를 타다가 얼떨결에 여기까지 오게 된 거라고。 어떤 책에 관해 물어보려 했는데 여기 사람들은 협조적이지 않네。 그럼 실례가 많았소。 수고。", "talkname0", 1);
Talk(97, "책을 훔치러 온 거였군！ 여봐라！ 이놈을 잡아라！", "talkname97", 0);
if TryBattle(94) == true then goto label0 end;
    Dead();
    do return end;
::label0::
    ModifyEvent(-2, 5, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 6, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 7, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 8, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 9, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    ModifyEvent(-2, 10, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
    jyx2_ReplaceSceneObject("","NPC/神龙弟子5","");
    jyx2_ReplaceSceneObject("","NPC/神龙弟子6","");
    jyx2_ReplaceSceneObject("","NPC/神龙弟子7","");
    jyx2_ReplaceSceneObject("","NPC/神龙弟子8","");
    jyx2_ReplaceSceneObject("","NPC/神龙弟子9","");
    jyx2_ReplaceSceneObject("","NPC/神龙弟子10","");
    LightScence();
    Talk(0, "하늘이 도왔다 보다！ 내가 찾는 책이 있을지도 몰라。 들어가서 물어보자！", "talkname0", 1);
    AddRepute(1);
do return end;
