Talk(25, "공자가 날 급히 만나려는 이유가 뭐지？", "talkname25", 0);
Talk(0, "당신이 교주？ 이렇게 젊은 교주가 있다니！ 보톡스라도 맞았나？", "talkname0", 1);
Talk(25, "공자가 무슨 말을 하는지 소녀는 도무지 알아듣지 못하겠어요。", "talkname25", 0);
Talk(0, "교주께 한 사람의 소식을 물어보러 왔소。", "talkname0", 1);
Talk(25, "공자가 알고 싶은 사람이 누구죠？", "talkname25", 0);
Talk(0, "위소보。", "talkname0", 1);
Talk(25, "공자， 누구한테 들었어요？", "talkname25", 0);
Talk(0, "신용교 홍교주。", "talkname0", 1);
Talk(25, "흥！ 신룡교의 첩자로군！ 위공자를 찾고 싶다면 나부터 때려눕히고 나서 다시 이야기해라！", "talkname25", 0);
Talk(0, "어떻게 하면 책장 넘기듯이 태세 전환이 빨라？", "talkname0", 1);
if TryBattle(98) == true then goto label0 end;
    Dead();
    do return end;
::label0::
    ModifyEvent(-2, -2, -2, -2, 617, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 0, -2, -2, 619, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 1, -2, -2, 619, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 2, -2, -2, 619, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 3, -2, -2, 619, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(-2, 4, -2, -2, 619, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(71, 3, -2, -2, 611, -1, -1, -2, -2, -2, -2, -2, -2);
    LightScence();
    Talk(0, "왜 항상 다들 싸우고 싶어 안달이야？ 말하기 싫으면 더는 강요하지 않겠다。", "talkname0", 1);
    Talk(25, "능청스럽게 굴지 말고 어서 죽여라！", "talkname25", 0);
    Talk(0, "묘족 여자는 성격이 화끈하군。 위소보를 찾는 건 \"녹정기\" 를 찾기 위해서요。", "talkname0", 1);
    Talk(25, "하가 놈은 어딨지？ 신룡교의 힘을 이용해 교주직을 빼앗으려는 거지？", "talkname25", 0);
    Talk(0, "무슨 소리요？ 교주 자리라니。", "talkname0", 1);
    Talk(25, "배신자 하철수의 사주를 받은 게 아니더냐？", "talkname25", 0);
    Talk(0, "아니오！ \"녹정기\" 라는 책을 찾는데 홍교주가 말하길 위소보가 책을 훔쳐 여기로 달아났다고 했소。", "talkname0", 1);
    Talk(25, "위 공자가 훔친 건 \"42장경\" 이지 \"녹정기\" 를 훔치진 않았어。", "talkname25", 0);
    Talk(0, "그럼 위소보는 어딨소？", "talkname0", 1);
    Talk(25, "아름다운 일곱 명의 부인들과 행복한 시간을 즐기고 있겠지。 나도 어딨는지 모른다。", "talkname25", 0);
    Talk(0, "흠…홍교주가 왜 날 속였을까？…", "talkname0", 1);
    Talk(25, "영문도 모른 채 이용당하다니 정말 멍청하군！ 위소보를 죽이고 \"42장경\"을 찾으려는 속셈이지！ 또 날 죽인 뒤 교주직을 하철수에게 계승해 이용하려는 거야。", "talkname25", 0);
    Talk(0, "… 날 속이다니！ 간악한 놈！ 쓴맛을 보여줄 테다！！", "talkname0", 1);
    Talk(25, "첩자로 오인해서 공격한 건 미안해。 공자， 나 남봉황의 도움이 필요하면 말만 해。", "talkname25", 0);
    Talk(0, "뭐， 나도 오해해서 잘못했으니까。", "talkname0", 1);
    Talk(25, "공자는 얼굴도 잘생기고 무공도 강하니 같이 강호에 나가고 싶어！", "talkname25", 0);
    Talk(0, "묘족 여자는 자신의 감정을 정말 솔직하게 들어내는군！'", "talkname0", 1);
    AddRepute(1);
    ChangeMMapMusic(3);
    if AskJoin () == true then goto label1 end;
        Talk(0, "마음은 고맙지만 불초한 나 때문에 아리따운 청춘을 낭비하지 마시오。", "talkname0", 1);
        do return end;
::label1::
        if TeamIsFull() == false then goto label2 end;
            Talk(25, "공자의 동료가 많으니 소녀가 함께 갈 수 없겠어요。", "talkname25", 0);
            do return end;
::label2::
            Talk(0, "낭자와 같은 미인과 다닐 수 있다면 큰 영광이지！", "talkname0", 1);
            DarkScence();
            jyx2_ReplaceSceneObject("", "NPC/lanfenghuang", "");--蓝凤凰加入
            ModifyEvent(-2, -2, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
            LightScence();
            Join(25);
do return end;
