ModifyEvent(-2, -2, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);
ScenceFromTo(33, 26, 21, 26);
jyx2_CameraFollow("Level/NPC/battleNPC/岳不群");
Talk(19, "여러분！ 매년 우리 화산에서 함께 모여 이 무림대회를 개최하니 이를 화산의 큰 영광으로 생각합니다。 올해 악 모는 특별히 소림사 방장 현자 대사를 초청하여 올해 \"화산논검\"의 주관을 맡길까 히오。", "talkname19", 0);
Talk(70, "아미타불！ 여러분이 저 현자를 높게 평가해 주셔서 올해는 제가 여러분들을 위해 봉사하겠습니다。 올해도 예년과 마찬가지로 화산에 초대받은 영웅들은 새로운 무림의 맹주가 되어 \"신장\"을 보관할 자격을 얻게 되오。 이제 저는 아무도 도전하지 않을 때까지 대회의 시작을 선포하겠소。 원한다면 누구나 나와서 겨룰 수 있습니다。", "talkname70", 4);
Talk(19, "어느 영웅이 먼저 도전을 받겠소？ …… 도전에 응할 사람이 없소？……", "talkname19", 0);
ScenceFromTo(21, 26, 33, 26);
jyx2_CameraFollowPlayer();
Talk(0, "좋아， 그럼 제가 먼저 도전하겠소。", "talkname0", 1);
WalkFromTo(33, 26, 25, 26);
jyx2_WalkFromTo(-1,2526);
SetRoleFace(2);
Talk(0, "어떤 영웅이 다음 가르침을 주시겠소。", "talkname0", 1);
FightForTop();
do return end;
